### ISSUE TITLE
Call to a member function setWidth() on string

### ISSUE THREAD

**Issue by EnzephaloN** [quellenform/t3x-bootstrap-package-iconpack#3]
Installed tx-iconpack, tx-iconpack-fontawesome and tx-bootstrap-package-iconpack on my TYPO3 12.4.20

If I set "Icon Set" of a page, the frontend gives a server error "Call to a member function setWidth() on string".

If I unset "Icon Set", the server error is gone.

Hope you can find this issue.

Best regards
EnzephaloN

**Comment by stephankellermayr** [comment]
Unfortunately, I cannot reproduce the error you mentioned.

Perhaps a complete error log would be helpful.  
It would also be helpful to know which extension versions you are using here.

Please also check whether you have integrated the TypoScript correctly and also clear the cache.

**Comment by EnzephaloN** [comment]
Hello and thank you for answering

Because of unknown magic, now it works...
